# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(510, 317)
        widget.setMinimumSize(QtCore.QSize(510, 317))
        widget.setMaximumSize(QtCore.QSize(562, 358))
        widget.setStyleSheet("\n"
"QPushButton:hover{\n"
"    background-color: rgb(196, 204, 255);\n"
"}\n"
"QComboBox:hover{\n"
"background-color: rgb(196, 204, 255);\n"
"}")
        self.groupBox = QtWidgets.QGroupBox(widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 481, 61))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 24, 60, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(55, 24, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(290, 20, 75, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushBautton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushBautton_2.setGeometry(QtCore.QRect(390, 20, 75, 26))
        self.pushBautton_2.setObjectName("pushBautton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(widget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 75, 481, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 20, 95, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 20, 95, 26))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 20, 95, 26))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 60, 95, 26))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 60, 95, 26))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(270, 60, 95, 26))
        self.pushButton_8.setObjectName("pushButton_8")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(380, 20, 85, 21))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.groupBox_3 = QtWidgets.QGroupBox(widget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 481, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 461, 101))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Tool"))
        self.groupBox.setTitle(_translate("widget", "配置设置"))
        self.label_3.setText(_translate("widget", "串口："))
        self.pushButton.setText(_translate("widget", "连接"))
        self.pushBautton_2.setText(_translate("widget", "断开"))
        self.groupBox_2.setTitle(_translate("widget", "Command"))
        self.pushButton_2.setText(_translate("widget", "整机复位"))
        self.pushButton_3.setText(_translate("widget", "气缸下压"))
        self.pushButton_4.setText(_translate("widget", "1#治具旋转"))
        self.pushButton_6.setText(_translate("widget", "退出单步调试"))
        self.pushButton_7.setText(_translate("widget", "气缸上升"))
        self.pushButton_8.setText(_translate("widget", "2#治具旋转"))
        self.checkBox.setText(_translate("widget", "开启光栅"))
        self.groupBox_3.setTitle(_translate("widget", "Receive"))
